# This file contains default non-project-specific settings for 'stack', used
# in all projects.  For more information about stack's configuration, see
# http://docs.haskellstack.org/en/stable/yaml_configuration/
#
templates:
  params:
    author-name: Carl Patenaude-Poulin
    author-email: carl.patenaudepoulin@mail.mcgill.ca
    github-username: lilred
